import '../app/globals.css'
import { Poppins } from 'next/font/google'
const poppins = Poppins({ subsets: ['latin'], weight: '400' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <main className={poppins.className + ' bg-gray-100 min-h-screen'}>{children}</main>
    </>
  )
}
